name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "0 10 * * 1-5"  # Ejecutar a las 10 AM de lunes a viernes
  workflow_dispatch:
    inputs:
      fileType:
        description: 'Tipo de archivo a ejecutar'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - about
          - careers
          - home
          - services
          - work

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: |
        FILE_TYPE="${{ github.event.inputs.fileType }}"
        if [ "$FILE_TYPE" == "all" ]; then
          npx playwright test --project=chromium
        else
          npx playwright test tests/$FILE_TYPE.spec.js --project=chromium
        fi
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/