name: Playwright Tests (Push and Schedule)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:  
      image: mcr.microsoft.com/playwright:v1.46.1-jammy  

    steps:
    - uses: actions/checkout@v4

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
